# Site settings
site: jumpuetta
title: 个人博客
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "人必须忠于自己 乔伊 不能违背自己的本性，带着杀戮活下去很艰难，这条路没有退路，是对是错你都得背负，直至一生。现在快回去找你妈妈，告诉她一切都好，山谷里再也不会有枪声了"  
baseurl: ""
author: jumpuetta
url: "http://jumpuetta.github.io"  

# About/contact
owner: 
  name: "jumpuetta"
  email: jumpuetta@163.com
  bio: "个人博客"

# Data
gavatar: img/logo.png
favicon: img/logo.png

douban_username:  
twitter_username: 
github_username: jumpuetta
facebook_username: 
weibo_username: 
zhihu_username:

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input:  GFM
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "jumpuetta"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: jumpuetta
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: jumpuetta
    repo: blog-comments
    oauth:
        client_id: 2502377ca3ce37fcc72b
        client_secret: ce54371fc8a57d3f7aae0816705f1808d11b6020
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: jumpuetta
    repo: blog-comments
    clientID: 2502377ca3ce37fcc72b
    clientSecret: ce54371fc8a57d3f7aae0816705f1808d11b6020
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation